name: Building Codelab from "codelab.md"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    paths: 'codelab.md'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v5.0.0
      - name: Installing claat @ latest
        run: go install github.com/googlecodelabs/tools/claat@latest
      - name: Making the HTML
        run: claat export codelab.md
      - name: Installing claat @ latest
        run: git add .
      - name: Installing claat @ latest
        run: git commit -m "Added the codelab HTML"
      - name: Installing claat @ latest
        run: git push origin codelab
          
        

     
