name: Codelab Export

on:
  push:
    paths:
      - 'codelab.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Important: This is needed to push back to the repo

      - name: Setup Go
        uses: actions/setup-go@v5

      - name: Install claat
        run: go install github.com/googlecodelabs/tools/claat@latest

      - name: Export codelab
        run: |
          claat export codelab.md

      - name: Push back to the repo
        uses: zyrouge/github-push-action@main
        with:
            github-token: $${{secrets.GH_PAT}}
            verbose: true
