name: Codelab Export

on:
  push:
    paths:
      - 'codelab.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Important: This is needed to push back to the repo

      - name: Setup Go
        uses: actions/setup-go@v5

      - name: Install claat
        run: go install github.com/googlecodelabs/tools/claat@latest

      - name: Export codelab
        run: |
          claat export codelab.md
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update codelab output" || echo "No changes to commit"
          git push origin HEAD:refs/heads/${{ github.head_ref }} --force
        env:
          GH_PAT: ${{ secrets.GH_PAT }}