name: Codelab Export

on:
  push:
    branches:
      - codelab
    paths:
      - 'codelab.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: codelab
          fetch-depth: 0  # Important: This is needed to push back to the repo

      - name: Setup Go
        uses: actions/setup-go@v5

      - name: Install claat
        run: go install github.com/googlecodelabs/tools/claat@latest

      - name: Export codelab
        run: |
          claat export codelab.md

      - name: Push back
        run: |
          git config user.name codelab-bot
          git config user.email nischalon10@gmail.com
          mv codelab-4-codelab-markdown/* .
          git add .
          git commit -m "Adding Codelab"
          git checkout codelab-page
          git checkout codelab index.html codelab.json
          git add .
          git commit -m "Updated the HTML and Json"
          git push https://nischalon10:${{secrets.GH_PAT}}@github.com/nischalon10/codelabtesting codelab-page
          git checkout codelab
          git reset --hard HEAD^
          rm 
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
